# Generated by Django 3.2.5 on 2024-06-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=250)),
                ('design_version', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Design',
            },
        ),
        migrations.CreateModel(
            name='DesignPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_portfolio', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
                ('designs', models.ManyToManyField(to='product_studio.Design')),
            ],
            options={
                'verbose_name': 'Design Portfolio',
                'verbose_name_plural': 'Design Portfolios',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
                ('colors', models.ManyToManyField(to='product_studio.Color')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_studio.producttype')),
                ('sizes', models.ManyToManyField(to='product_studio.Size')),
            ],
            options={
                'verbose_name': 'Product Part',
                'verbose_name_plural': 'Product Parts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('color', models.ManyToManyField(to='product_studio.Color')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_studio.design')),
                ('design_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_studio.designportfolio')),
                ('product_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_studio.productpart')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_studio.producttype')),
                ('size', models.ManyToManyField(to='product_studio.Size')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
