# Generated by Django 3.2.5 on 2024-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaireAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Faire API',
                'verbose_name_plural': 'Faire API',
            },
        ),
        migrations.CreateModel(
            name='FaireAPIEndpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=100)),
                ('endpoint_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Faire API Endpoints',
                'verbose_name_plural': 'Faire API Endpointss',
            },
        ),
    ]
