# Generated by Django 3.2.5 on 2024-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_channel', models.CharField(max_length=50, verbose_name='Sales Channel')),
                ('display_id', models.CharField(max_length=100, unique=True, verbose_name='Display ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('customer', models.CharField(max_length=100, verbose_name='Customer')),
                ('brand_discounts', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Discounts')),
                ('original_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Order ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Initiated At')),
                ('processing_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing At')),
                ('expected_ship_date', models.DateField(blank=True, null=True, verbose_name='Expected Ship Date')),
                ('requested_ship_date', models.DateField(blank=True, null=True, verbose_name='Requested_Ship_Date')),
                ('ship_after', models.DateField(blank=True, null=True, verbose_name='Ship After')),
                ('item_subtotal', models.IntegerField(blank=True, null=True, verbose_name='Item Subtotal')),
                ('payout_fee_percentage', models.IntegerField(blank=True, null=True, verbose_name='Payout Fee Percentage')),
                ('payout_fee_cost', models.IntegerField(blank=True, null=True, verbose_name='Payout Fee Cost')),
                ('commission_percentage', models.IntegerField(blank=True, null=True, verbose_name='Commission Percentage')),
                ('commission_cost', models.IntegerField(blank=True, null=True, verbose_name='Commission Cost')),
                ('total_payout', models.IntegerField(blank=True, null=True, verbose_name='Total Payout')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
            },
        ),
    ]
